[project]
name = "comfyui-checkpoint-loader-with-loras"
description = "A ComfyUI custom node that loads checkpoints and allows applying up to three LoRAs with adjustable strengths."
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/Izunata-kagino/ComfyUI-Checkpoint-Loader-With-LoRAs"

[tool.comfy]
PublisherId = "Izunata-kagino"
DisplayName = "ComfyUI Checkpoint Loader With LoRAs"